name: Fork Repos

on:
  push:
    branches:
      - main  # 触发条件：当代码提交到 main 分支时触发

jobs:
  fork_repos:
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版本作为运行环境

    steps:
    - name: Checkout repository  # 检出代码仓库
      uses: actions/checkout@v2  # 使用官方的 checkout 动作

    - name: Read owners_repos from file  # 从文件中读取 owners_repos 列表
      run: |
        owners_repos_file="owners_repos.txt"
        if [ ! -f "$owners_repos_file" ]; then
            echo "Error: $owners_repos_file does not exist."
            exit 1
        fi
        while IFS= read -r owner_repo; do
            echo "Forking $owner_repo"
            curl -X POST -H "Authorization: token ${{ secrets.PERSONAL_TOKEN }}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/$owner_repo/forks"
            sleep 5
        done < "$owners_repos_file"

      shell: bash  # 使用 bash shell
