name: Auto Fork

on:
  workflow_dispatch:

jobs:
  fork:
    runs-on: ubuntu-latest
    steps:
    - name: Fork repository
      uses: octokit/request-action@v2.x
      with:
        route: POST /repos/:owner/:repo/forks
        owner: CVEProject # 原始仓库的拥有者用户名
        repo: cvelist # 原始仓库的名称
        token: ${{ secrets.PERSONAL_TOKEN }} # 替换为你的 Personal Access Token
        mediaType: application/vnd.github.v3+json
