name: Batch Auto Fork

on:
  workflow_dispatch:

jobs:
  fork:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Read owners_repos file
      id: read_owners_repos
      run: |
        echo "::set-output name=owners_repos::$(cat owners_repos.txt)"
        
    - name: Batch Fork repositories
      run: |
        # 从输出中获取 owners_repos 列表
        owners_repos=$(echo "${{ steps.read_owners_repos.outputs.owners_repos }}")
        
        echo "Owners and Repos: $owners_repos" # 调试输出
        
        # 按行分割 owners_repos
        IFS=$'\n' read -rd '' -a repos_array <<< "$owners_repos"
        
        # 循环遍历 owner 和 repo 列表
        for owner_repo in "${repos_array[@]}"; do
          echo "Owner Repo: $owner_repo" # 调试输出
          owner=$(echo $owner_repo | cut -d ' ' -f1) # 提取 owner
          repo=$(echo $owner_repo | cut -d ' ' -f2) # 提取 repo
          echo $owner
          echo $repo
        done
