name: Fork Repository

on:
  push:
    branches:
      - main  # 触发条件可以根据需要进行调整

jobs:
  fork_repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Fork Repository
        id: fork_repo
        run: |
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER="CVEProject"  # 原始仓库的拥有者
          REPO_NAME="cvelist"  # 原始仓库的名称
          API_URL="https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/forks"
          RESPONSE=$(curl -X POST -H "Authorization: token $TOKEN" $API_URL)
          echo "::set-output name=forked_repo::$RESPONSE"
